name: PR Jobs

on:
  pull_request:

jobs:
  pytest:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/ci.txt
      - name: Test with pytest
        run: |
          pytest

  black:
    name: Python Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Run black
      uses: psf/black@af0ba72a73598c76189d6dd1b21d8532255d5942 # v25
      with:
        options: ". --check --verbose"

  pylint:
    name: Python Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/ci.txt
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py' | grep -v dnspython)

  eslint:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
    - name: Setup Bun and Run ESLint
      run: |
        bun init -y
        bun add eslint @eslint/js
        bunx eslint

  stylelint:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - name: Run stylelint
        run: |
          bun init -y
          bun install stylelint stylelint-config-standard
          bunx stylelint static/css/*.css

  actionlint:
    name: 'Github Actions YAML Lint'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Download actionlint
      run: |
        VERSION="1.7.7"
        ARCH=$(dpkg --print-architecture)
        wget -c "https://github.com/rhysd/actionlint/releases/download/v${VERSION}/actionlint_${VERSION}_linux_${ARCH}.tar.gz" -O - | tar -xz
    - name: Check workflow files
      run: ./actionlint -shellcheck= -pyflakes= -color
